/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as ContributeRouteImport } from './routes/contribute'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResearchIndexRouteImport } from './routes/research.index'
import { Route as TopicsSlugRouteImport } from './routes/topics.$slug'
import { Route as ResearchChar123slugChar125DotmdRouteImport } from './routes/research.{$slug}[.]md'
import { Route as ResearchSlugRouteImport } from './routes/research.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeRoute = ContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIndexRoute = ResearchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResearchRoute,
} as any)
const TopicsSlugRoute = TopicsSlugRouteImport.update({
  id: '/topics/$slug',
  path: '/topics/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchChar123slugChar125DotmdRoute =
  ResearchChar123slugChar125DotmdRouteImport.update({
    id: '/{$slug}.md',
    path: '/{$slug}.md',
    getParentRoute: () => ResearchRoute,
  } as any)
const ResearchSlugRoute = ResearchSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResearchRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contribute': typeof ContributeRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/research': typeof ResearchRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/research/{$slug}.md': typeof ResearchChar123slugChar125DotmdRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/research/': typeof ResearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contribute': typeof ContributeRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/research/{$slug}.md': typeof ResearchChar123slugChar125DotmdRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/research': typeof ResearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contribute': typeof ContributeRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/research': typeof ResearchRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/research/{$slug}.md': typeof ResearchChar123slugChar125DotmdRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/research/': typeof ResearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contribute'
    | '/llms.txt'
    | '/research'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/research/$slug'
    | '/research/{$slug}.md'
    | '/topics/$slug'
    | '/research/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contribute'
    | '/llms.txt'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/research/$slug'
    | '/research/{$slug}.md'
    | '/topics/$slug'
    | '/research'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contribute'
    | '/llms.txt'
    | '/research'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/research/$slug'
    | '/research/{$slug}.md'
    | '/topics/$slug'
    | '/research/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContributeRoute: typeof ContributeRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  ResearchRoute: typeof ResearchRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TopicsSlugRoute: typeof TopicsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute': {
      id: '/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof ContributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/': {
      id: '/research/'
      path: '/'
      fullPath: '/research/'
      preLoaderRoute: typeof ResearchIndexRouteImport
      parentRoute: typeof ResearchRoute
    }
    '/topics/$slug': {
      id: '/topics/$slug'
      path: '/topics/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof TopicsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/{$slug}.md': {
      id: '/research/{$slug}.md'
      path: '/{$slug}.md'
      fullPath: '/research/{$slug}.md'
      preLoaderRoute: typeof ResearchChar123slugChar125DotmdRouteImport
      parentRoute: typeof ResearchRoute
    }
    '/research/$slug': {
      id: '/research/$slug'
      path: '/$slug'
      fullPath: '/research/$slug'
      preLoaderRoute: typeof ResearchSlugRouteImport
      parentRoute: typeof ResearchRoute
    }
  }
}

interface ResearchRouteChildren {
  ResearchSlugRoute: typeof ResearchSlugRoute
  ResearchChar123slugChar125DotmdRoute: typeof ResearchChar123slugChar125DotmdRoute
  ResearchIndexRoute: typeof ResearchIndexRoute
}

const ResearchRouteChildren: ResearchRouteChildren = {
  ResearchSlugRoute: ResearchSlugRoute,
  ResearchChar123slugChar125DotmdRoute: ResearchChar123slugChar125DotmdRoute,
  ResearchIndexRoute: ResearchIndexRoute,
}

const ResearchRouteWithChildren = ResearchRoute._addFileChildren(
  ResearchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContributeRoute: ContributeRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ResearchRoute: ResearchRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TopicsSlugRoute: TopicsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
