/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteImport } from './routes/{-$locale}'
import { Route as VersionDottxtRouteImport } from './routes/version[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}.index'
import { Route as Char123LocaleChar125ResearchRouteImport } from './routes/{-$locale}.research'
import { Route as Char123LocaleChar125ContributeRouteImport } from './routes/{-$locale}.contribute'
import { Route as Char123LocaleChar125AboutRouteImport } from './routes/{-$locale}.about'
import { Route as TopicsSlugRouteImport } from './routes/topics.$slug'
import { Route as Char123LocaleChar125ResearchIndexRouteImport } from './routes/{-$locale}.research.index'
import { Route as Char123LocaleChar125ResearchChar123slugChar125DotmdRouteImport } from './routes/{-$locale}.research.{$slug}[.]md'
import { Route as Char123LocaleChar125ResearchSlugRouteImport } from './routes/{-$locale}.research.$slug'

const Char123LocaleChar125Route = Char123LocaleChar125RouteImport.update({
  id: '/{-$locale}',
  path: '/{-$locale}',
  getParentRoute: () => rootRouteImport,
} as any)
const VersionDottxtRoute = VersionDottxtRouteImport.update({
  id: '/version.txt',
  path: '/version.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ResearchRoute =
  Char123LocaleChar125ResearchRouteImport.update({
    id: '/research',
    path: '/research',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ContributeRoute =
  Char123LocaleChar125ContributeRouteImport.update({
    id: '/contribute',
    path: '/contribute',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125AboutRoute =
  Char123LocaleChar125AboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const TopicsSlugRoute = TopicsSlugRouteImport.update({
  id: '/topics/$slug',
  path: '/topics/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125ResearchIndexRoute =
  Char123LocaleChar125ResearchIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125ResearchRoute,
  } as any)
const Char123LocaleChar125ResearchChar123slugChar125DotmdRoute =
  Char123LocaleChar125ResearchChar123slugChar125DotmdRouteImport.update({
    id: '/{$slug}.md',
    path: '/{$slug}.md',
    getParentRoute: () => Char123LocaleChar125ResearchRoute,
  } as any)
const Char123LocaleChar125ResearchSlugRoute =
  Char123LocaleChar125ResearchSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => Char123LocaleChar125ResearchRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/version.txt': typeof VersionDottxtRoute
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/topics/$slug': typeof TopicsSlugRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/contribute': typeof Char123LocaleChar125ContributeRoute
  '/{-$locale}/research': typeof Char123LocaleChar125ResearchRouteWithChildren
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/research/$slug': typeof Char123LocaleChar125ResearchSlugRoute
  '/{-$locale}/research/{$slug}.md': typeof Char123LocaleChar125ResearchChar123slugChar125DotmdRoute
  '/{-$locale}/research/': typeof Char123LocaleChar125ResearchIndexRoute
}
export interface FileRoutesByTo {
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/version.txt': typeof VersionDottxtRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/contribute': typeof Char123LocaleChar125ContributeRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/research/$slug': typeof Char123LocaleChar125ResearchSlugRoute
  '/{-$locale}/research/{$slug}.md': typeof Char123LocaleChar125ResearchChar123slugChar125DotmdRoute
  '/{-$locale}/research': typeof Char123LocaleChar125ResearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/version.txt': typeof VersionDottxtRoute
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/topics/$slug': typeof TopicsSlugRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/contribute': typeof Char123LocaleChar125ContributeRoute
  '/{-$locale}/research': typeof Char123LocaleChar125ResearchRouteWithChildren
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/research/$slug': typeof Char123LocaleChar125ResearchSlugRoute
  '/{-$locale}/research/{$slug}.md': typeof Char123LocaleChar125ResearchChar123slugChar125DotmdRoute
  '/{-$locale}/research/': typeof Char123LocaleChar125ResearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/llms.txt'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/version.txt'
    | '/{-$locale}'
    | '/topics/$slug'
    | '/{-$locale}/about'
    | '/{-$locale}/contribute'
    | '/{-$locale}/research'
    | '/{-$locale}/'
    | '/{-$locale}/research/$slug'
    | '/{-$locale}/research/{$slug}.md'
    | '/{-$locale}/research/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/llms.txt'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/version.txt'
    | '/topics/$slug'
    | '/{-$locale}/about'
    | '/{-$locale}/contribute'
    | '/{-$locale}'
    | '/{-$locale}/research/$slug'
    | '/{-$locale}/research/{$slug}.md'
    | '/{-$locale}/research'
  id:
    | '__root__'
    | '/llms.txt'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/version.txt'
    | '/{-$locale}'
    | '/topics/$slug'
    | '/{-$locale}/about'
    | '/{-$locale}/contribute'
    | '/{-$locale}/research'
    | '/{-$locale}/'
    | '/{-$locale}/research/$slug'
    | '/{-$locale}/research/{$slug}.md'
    | '/{-$locale}/research/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VersionDottxtRoute: typeof VersionDottxtRoute
  Char123LocaleChar125Route: typeof Char123LocaleChar125RouteWithChildren
  TopicsSlugRoute: typeof TopicsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/version.txt': {
      id: '/version.txt'
      path: '/version.txt'
      fullPath: '/version.txt'
      preLoaderRoute: typeof VersionDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/research': {
      id: '/{-$locale}/research'
      path: '/research'
      fullPath: '/{-$locale}/research'
      preLoaderRoute: typeof Char123LocaleChar125ResearchRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/contribute': {
      id: '/{-$locale}/contribute'
      path: '/contribute'
      fullPath: '/{-$locale}/contribute'
      preLoaderRoute: typeof Char123LocaleChar125ContributeRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/about': {
      id: '/{-$locale}/about'
      path: '/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof Char123LocaleChar125AboutRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/topics/$slug': {
      id: '/topics/$slug'
      path: '/topics/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof TopicsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/research/': {
      id: '/{-$locale}/research/'
      path: '/'
      fullPath: '/{-$locale}/research/'
      preLoaderRoute: typeof Char123LocaleChar125ResearchIndexRouteImport
      parentRoute: typeof Char123LocaleChar125ResearchRoute
    }
    '/{-$locale}/research/{$slug}.md': {
      id: '/{-$locale}/research/{$slug}.md'
      path: '/{$slug}.md'
      fullPath: '/{-$locale}/research/{$slug}.md'
      preLoaderRoute: typeof Char123LocaleChar125ResearchChar123slugChar125DotmdRouteImport
      parentRoute: typeof Char123LocaleChar125ResearchRoute
    }
    '/{-$locale}/research/$slug': {
      id: '/{-$locale}/research/$slug'
      path: '/$slug'
      fullPath: '/{-$locale}/research/$slug'
      preLoaderRoute: typeof Char123LocaleChar125ResearchSlugRouteImport
      parentRoute: typeof Char123LocaleChar125ResearchRoute
    }
  }
}

interface Char123LocaleChar125ResearchRouteChildren {
  Char123LocaleChar125ResearchSlugRoute: typeof Char123LocaleChar125ResearchSlugRoute
  Char123LocaleChar125ResearchChar123slugChar125DotmdRoute: typeof Char123LocaleChar125ResearchChar123slugChar125DotmdRoute
  Char123LocaleChar125ResearchIndexRoute: typeof Char123LocaleChar125ResearchIndexRoute
}

const Char123LocaleChar125ResearchRouteChildren: Char123LocaleChar125ResearchRouteChildren =
  {
    Char123LocaleChar125ResearchSlugRoute:
      Char123LocaleChar125ResearchSlugRoute,
    Char123LocaleChar125ResearchChar123slugChar125DotmdRoute:
      Char123LocaleChar125ResearchChar123slugChar125DotmdRoute,
    Char123LocaleChar125ResearchIndexRoute:
      Char123LocaleChar125ResearchIndexRoute,
  }

const Char123LocaleChar125ResearchRouteWithChildren =
  Char123LocaleChar125ResearchRoute._addFileChildren(
    Char123LocaleChar125ResearchRouteChildren,
  )

interface Char123LocaleChar125RouteChildren {
  Char123LocaleChar125AboutRoute: typeof Char123LocaleChar125AboutRoute
  Char123LocaleChar125ContributeRoute: typeof Char123LocaleChar125ContributeRoute
  Char123LocaleChar125ResearchRoute: typeof Char123LocaleChar125ResearchRouteWithChildren
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
}

const Char123LocaleChar125RouteChildren: Char123LocaleChar125RouteChildren = {
  Char123LocaleChar125AboutRoute: Char123LocaleChar125AboutRoute,
  Char123LocaleChar125ContributeRoute: Char123LocaleChar125ContributeRoute,
  Char123LocaleChar125ResearchRoute:
    Char123LocaleChar125ResearchRouteWithChildren,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
}

const Char123LocaleChar125RouteWithChildren =
  Char123LocaleChar125Route._addFileChildren(Char123LocaleChar125RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LlmsDottxtRoute: LlmsDottxtRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VersionDottxtRoute: VersionDottxtRoute,
  Char123LocaleChar125Route: Char123LocaleChar125RouteWithChildren,
  TopicsSlugRoute: TopicsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
